### ISSUE TITLE
内容不满一屏的时候无法滑动？有对应的属性可以设置吗？

### ISSUE THREAD

**Issue by BestKai** [fluttercandies/pull_to_refresh_notification#1]

**Comment by zmtzawqlp** [comment]
请提供一下 简单重现 的 demo，是没法下拉刷新？ 不应该哇

**Comment by BestKai** [comment]
@zmtzawqlp 把 pull_to_refresh_appbar.dart  文件中的listlength 改小点，整个页面无法下拉。

**Comment by zmtzawqlp** [comment]
@BestKai 你可以把这个改成一直可以滚动
![image](https://user-images.githubusercontent.com/16477333/55383176-1ccb1680-555a-11e9-89c4-9f1fa0bbfa61.png)
