### ISSUE TITLE
为什么我设置的滑动监听，没有反应？

### ISSUE THREAD

**Issue by qinlang122** [fluttercandies/pull_to_refresh_notification#10]
代码如下，打印一直没有输出。

`Scaffold(
      appBar: new MyAppBar(
        child: Container(
          color: Colors.white30,
          child: Text("Title"),
        ),
      ),
      body: PullToRefreshNotification(
        onRefresh: _onRefresh,
        maxDragOffset: 250.0,
        notificationPredicate: (info) {
          print("---1----->${info?.metrics?.pixels}");
          return true;
        },
        child: CustomScrollView(
          controller: _scrollControler,
          slivers: <Widget>[
            PullToRefreshContainer((info) {
              var offset = info?.dragOffset ?? 0.0;
              return SliverToBoxAdapter(
                child: Stack(
                  children: <Widget>[
                    new Container(
                      height: 240 + offset,
                      width: double.infinity,
                      child: Image.asset(
                        "images/img_mine_top_bg.jpg",
                        fit: BoxFit.cover,
                      ),
                    ),
                  ],
                ),
              );
            }),
            SliverList(
              delegate: SliverChildListDelegate(_listItem()),
            )
          ],
        ),
      ),
    );`

**Comment by zmtzawqlp** [comment]
_onRefresh 看看这个你咋写 的

**Comment by qinlang122** [comment]
Future<bool> _onRefresh() async {
//    print("----->onRefresh");
    return true;
  }

原来里面那个打印没写，一直没有滚动回调，然后我随意加了那行打印，突然就可以了，然后再把那个打印屏蔽了，也变成一直可以了。迷之代码。
