### ISSUE TITLE
Typo refreshWiget

### ISSUE THREAD

**Issue by comerc** [fluttercandies/pull_to_refresh_notification#15]
```dart
class PullToRefreshScrollNotificationInfo {
  //...
  final Widget refreshWiget;
}
```

**Comment by zmtzawqlp** [comment]
thanks, i will correct it later as it's a breaking change

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/pull_to_refresh_notification/commit/c43e29e2421755cb2c340244e3727c5a0dee3791
