### ISSUE TITLE
Failed assertion: line 280 pos 12: '_notificationDragOffset == null': is not true.

### ISSUE THREAD

**Issue by qq329401134** [fluttercandies/pull_to_refresh_notification#2]
pull_to_refresh_header使用这个会出现上面的问题，不知什么意思，希望可以解答一下谢谢了

**Comment by zmtzawqlp** [comment]
不影响使用 _notificationDragOffset  在你拖动开始之前，一般是一定为null的，不为null的话 是因为可能你动画或者其他因素 没有结束
