### ISSUE TITLE
Show error and dismiss instead of wait for user input

### ISSUE THREAD

**Issue by naamapps** [fluttercandies/pull_to_refresh_notification#22]
Hey,
Thanks for the awesome package.
It would be great if you could add the option to show an error without waiting for user input.
Only show error and dismiss after a certain duration delay.

Thanks

**Comment by zmtzawqlp** [comment]
you can handle the status as you wish, demo just an demo, you can define it as anything you want

**Comment by naamapps** [comment]
@zmtzawqlp You implemented this on latest update.
Thanks!
Now all we need is a way to delay the pull back.
I didn't find a way to do this.
