### ISSUE TITLE
希望可以开放部分参数

### ISSUE THREAD

**Issue by DizzyYang** [fluttercandies/pull_to_refresh_notification#27]
希望可以开放此参数

// When the scroll ends, the duration of the refresh indicator's animation
// to the RefreshIndicator's displacement.
const Duration _kIndicatorSnapDuration = Duration(milliseconds: 150);

有些需求只是下拉放大图片。

现在回弹需要等待该时长。

很怪

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/pull_to_refresh_notification/blob/940efd89e14424279c43a7a0069a731591660e2a/lib/src/pull_to_refresh_notification.dart#L118

这个设置下

**Comment by DizzyYang** [comment]
pullBackDuration是回弹动画的时间

_kIndicatorSnapDuration是下拉后刷新状态下停留的时间

**Comment by zmtzawqlp** [comment]
> pullBackDuration是回弹动画的时间
> 
> _kIndicatorSnapDuration是下拉后刷新状态下停留的时间

刷新状态多久。。跟 onrefresh 多久返回有关系

**Comment by DizzyYang** [comment]
PullToRefreshNotification(
            onRefresh: () {
              return Future<bool>.delayed(Duration.zero, () {
                return true;
              });
            },
            pullBackOnRefresh: true,
            maxDragOffset: 200,
            pullBackCurve: Curves.linear,
            pullBackDuration: const Duration(milliseconds: 300),
            child: PullToRefreshContainer((info) {
              double offset = info?.dragOffset ?? 0;
              return Container(
                width: double.infinity,
                height: 220 + offset,
                color: Colors.red,
              );
            }),
          ),


以上是我的使用场景。
maxDragOffset：下拉最大距离。
pullBackDuration：回弹动画时长。

当我下拉到最大距离后，放手，会有停留时间。

当我修改为，
const Duration _kIndicatorSnapDuration = Duration.zero;

就没有停留时间了。

所以我希望可以开放此参数。

**Comment by zmtzawqlp** [comment]
那你完全可以不用这个组件呢。。你这个动作都没有刷新效果，你用ios 的物理效果就行了。

**Comment by DizzyYang** [comment]
<img width="622" alt="WX20220114-105709@2x" src="https://user-images.githubusercontent.com/8134160/149443915-583f4984-8dfb-4f60-92e8-babf831c5390.png">

可以看_show这个方法，是在执行 animateTo 后才调用了onRefresh

**Comment by zmtzawqlp** [comment]
我的意思是。你可以自己写。这是刷新组件。不是动画组件

**Comment by DizzyYang** [comment]
@zmtzawqlp

我明白你的意思。

单纯以刷新组件来说，onRefresh的返回应该是可以控制停留时长的吧。

如果以测试的角度来看，后台50毫秒返回数据了，但是App停留了150毫秒，App端不看源码的话会很纳闷，怎么会停留这么长时间。
