### ISSUE TITLE
The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.

### ISSUE THREAD

**Issue by eleanors** [fluttercandies/pull_to_refresh_notification#3]

**Comment by zmtzawqlp** [comment]
@eleanors  you have used flutter version more than 1.5.8 ,right?  i suggest to use stable version of fultter, i will update api when stable version update

**Comment by NetFly-VPN** [comment]
> @eleanors you have used flutter version more than 1.5.8 ,right? i suggest to use stable version of fultter, i will update api when stable version update

Channel stable, v1.7.8+hotfix.3. The 1.7.8 has been stable. I occur the error

**Comment by zmtzawqlp** [comment]
```dart
  pull_to_refresh_notification:
    git:
      url: https://github.com/fluttercandies/pull_to_refresh_notification.git
      ref: dev
```
link it as this,  i will update codes to pub later

**Comment by zmtzawqlp** [comment]
base on v1.7.8 is ready in pub, please update it.
