### ISSUE TITLE
[3.13.0]  出错了 ,求更新下

### ISSUE THREAD

**Issue by huafsud** [fluttercandies/pull_to_refresh_notification#36]
### Content

pub.dev/pull_to_refresh_notification-3.0.1/lib/src/pull_to_refresh_notification.dart:326:20:
 Error: The method 'disallowGlow'
isn't defined for
                    the class 'OverscrollIndicatorNotification'.

**Comment by zmtzawqlp** [comment]
done, 3.1.0 is ready
